### ISSUE TITLE
ブランチ分けについて

### ISSUE THREAD

**Issue by Dk-Roar** [LunaChevalierGroup/elementProgram#61]
develop/ブランチにいろんなものが入ってきて、そろそろ混在してきました。
ここでブランチを分け、それぞれ目的に応じたソースだけをコミットするようにしてみようと思います。

ブランチの作成やコミット履歴を追う練習をすることが目的です。

■現状
```
develop/dfjkyrcq　（色々はいってる）
```

■変更後
```
develop/dfjkyrcq
┣ feature/~~~ (課題ごとに作成)
┣ feature/~~~
┣ feature/~~~
```

まず現状のdevelopから課題ごとにfeatureを作成します。
ブランチが作成できたら、課題に関係ないソースは削除してコミットし、プッシュを行います。
最終的には、各課題のブランチが存在し、それぞれのブランチには課題に関係するソースだけが残っていればOKです。

**Comment by dfjkyrcq** [comment]
featureの作成方法が分かりません。

**Comment by dfjkyrcq** [comment]
feature/FizzBuzzブランチを作成しました。featureブランチからFizzBuzzのファイル以外を削除したら削除したファイルがコミットされました。コミットされたものを削除するにはどうすればよいですか

**Comment by dfjkyrcq** [comment]
error: failed to push some refs to 'https://github.com/LunaChevalierGroup/elementProgram'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
このようなエラーが出てpushできなくなりました。
